version: "3.8"

x-base-settings: &base_service_settings
  tty: true
  user: node
  env_file: .env
  network_mode: host
  build: &base_build_settings
    context: .
  environment: &base_environment_settings
    # Colorize the terminal in the container if possible
    TERM: "${TERM:-}"
    NVIDIA_DRIVER_CAPABILITIES: all
  deploy:
    resources:
      reservations:
        devices:
          - capabilities:
            - gpu

x-main-service-settings: &main_service_settings
  <<: *base_service_settings
  volumes:
    - "${PWD}:/opt/rapids/node:rw"
    - "/etc/fonts:/etc/fonts:ro"
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/usr/share/fonts:/usr/share/fonts:ro"
    - "/usr/share/icons:/usr/share/icons:ro"
    - "/etc/timezone:/etc/timezone"
    - "/etc/localtime:/etc/localtime"
    - "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket"
    - "${XDG_RUNTIME_DIR:-/run/user/$UID}:${XDG_RUNTIME_DIR:-/run/user/$UID}"
  working_dir: /opt/rapids/node
  environment: &main_environment_settings
    <<: *base_environment_settings
    # Use the host's X11 display
    DISPLAY: "${DISPLAY:-}"
    XAUTHORITY: "${XAUTHORITY:-}"
    XDG_SESSION_TYPE: "${XDG_SESSION_TYPE:-}"
    XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR:-/run/user/$UID}"
    DBUS_SESSION_BUS_ADDRESS: "${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/$UID/bus}"
  cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
  security_opt:
    - apparmor=unconfined


services:

  base:
    <<: *base_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-16.6.2}-cudagl${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/devel/01-base.Dockerfile
      args:
        UID: ${UID:-1000}
        NODE_VERSION: ${NODE_VERSION:-16.6.2}
        ADDITIONAL_GROUPS: "${ARCH_USER_GROUPS:---groups sudo}"
        FROM_IMAGE: ${ARCH_BASE_IMAGE:-}
        FROM_IMAGE_DEFAULT: nvidia/cudagl:${CUDA_VERSION:-11.2.2}-devel-${LINUX_VERSION:-ubuntu20.04}

  main:
    <<: *main_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-16.6.2}-cudagl${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/devel/02-main.Dockerfile
      args:
        FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-16.6.2}-cudagl${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}

  wrtc:
    <<: *main_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-16.6.2}-cudagl${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-wrtc-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/devel/03-wrtc.Dockerfile
      args:
        SCCACHE_REGION: "${SCCACHE_REGION:-}"
        SCCACHE_BUCKET: "${SCCACHE_BUCKET:-}"
        SCCACHE_CACHE_SIZE: "${SCCACHE_CACHE_SIZE:-}"
        SCCACHE_IDLE_TIMEOUT: "${SCCACHE_IDLE_TIMEOUT:-}"
        AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
        AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
        FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-16.6.2}-cudagl${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}

  nteract:
    <<: *main_service_settings
    image: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-16.6.2}-cudagl${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-nteract-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/devel/04-nteract.Dockerfile
      args:
        FROM_IMAGE: rapidsai/node:${RAPIDS_VERSION:-latest}-devel-node${NODE_VERSION:-16.6.2}-cudagl${CUDA_VERSION:-11.2.2}-${LINUX_VERSION:-ubuntu20.04}-wrtc-${ARCH:-amd64}
    environment:
      <<: *main_environment_settings
      QT_AUTO_SCREEN_SCALE_FACTOR: 0
    command: nteract
