version: "3.8"

x-base-settings: &base_service_settings
  tty: true
  env_file: .env
  network_mode: host
  build: &base_build_settings
    context: .
  environment: &base_environment_settings
    # Colorize the terminal in the container if possible
    TERM: "${TERM:-}"
  deploy:
    resources:
      reservations:
        devices:
          - capabilities:
            - gpu

x-main-service-settings: &main_service_settings
  <<: *base_service_settings
  build: &main_build_settings
    <<: *base_build_settings
    args: &main_build_args
      DEVEL_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-devel-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-packages-${ARCH:-amd64}
  environment: &main_environment_variables
    <<: *base_environment_settings
    # Use the host's X11 display
    DISPLAY: "${DISPLAY:-}"
    XAUTHORITY: "${XAUTHORITY:-}"
    XDG_SESSION_TYPE: "${XDG_SESSION_TYPE:-}"

services:

  cuda-base:
    <<: *base_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/runtime/base.Dockerfile
      args:
        UID: ${UID:-1000}
        ADDITIONAL_GROUPS: ${ARCH_USER_GROUPS:-}
        FROM_IMAGE: ${ARCH_BASE_IMAGE:-}
        FROM_IMAGE_DEFAULT: nvidia/cuda:${CUDA_VERSION:-11.4.2}-runtime-${LINUX_VERSION:-ubuntu20.04}
        DEVEL_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-devel-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}

  cudagl-base:
    <<: *base_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dockerfiles/runtime/base.Dockerfile
      args:
        UID: ${UID:-1000}
        ADDITIONAL_GROUPS: ${ARCH_USER_GROUPS:-}
        FROM_IMAGE: ${ARCH_BASE_IMAGE:-}
        FROM_IMAGE_DEFAULT: nvidia/cudagl:${CUDA_VERSION:-11.4.2}-runtime-${LINUX_VERSION:-ubuntu20.04}
        DEVEL_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-devel-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}

  main:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/main.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}

  demo:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-demo-${ARCH:-amd64}
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/demo.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}

  glfw:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-glfw-${ARCH:-amd64}
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/glfw.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}

  cudf:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-cudf-${ARCH:-amd64}
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/cudf.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}

  sql:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-sql-${ARCH:-amd64}
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/sql.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}

  cuml:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-cuml-${ARCH:-amd64}
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/cuml.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}

  cugraph:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-cugraph-${ARCH:-amd64}
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/cugraph.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}

  cuspatial:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-cuspatial-${ARCH:-amd64}
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/cuspatial.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-base-${ARCH:-amd64}

  notebook:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-notebook-${ARCH:-amd64}
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/notebook.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}
    volumes:
      - "/etc/fonts:/etc/fonts:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/usr/share/fonts:/usr/share/fonts:ro"
      - "/usr/share/icons:/usr/share/icons:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket"
      - "${XDG_RUNTIME_DIR:-/run/user/$UID}:${XDG_RUNTIME_DIR:-/run/user/$UID}"
    environment: &main_environment_settings
      # Colorize the terminal in the container if possible
      TERM: "${TERM:-}"
      NVIDIA_DRIVER_CAPABILITIES: all
      # Use the host's X11 display
      DISPLAY: "${DISPLAY:-}"
      XAUTHORITY: "${XAUTHORITY:-}"
      XDG_SESSION_TYPE: "${XDG_SESSION_TYPE:-}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR:-/run/user/$UID}"
      DBUS_SESSION_BUS_ADDRESS: "${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/$UID/bus}"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
