version: "3.8"

x-base-settings: &base_service_settings
  tty: true
  env_file: .env
  network_mode: host
  build: &base_build_settings
    context: .
  environment: &base_environment_settings
    # Colorize the terminal in the container if possible
    TERM: "${TERM:-}"
  deploy:
    resources:
      reservations:
        devices:
          - capabilities:
            - gpu

x-main-service-settings: &main_service_settings
  <<: *base_service_settings
  build: &main_build_settings
    <<: *base_build_settings
    args: &main_build_args
      DEVEL_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-devel-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-main
      BUILD_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-devel-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-packages
  environment: &main_environment_variables
    <<: *base_environment_settings
    # Use the host's X11 display
    DISPLAY: "${DISPLAY:-}"
    XAUTHORITY: "${XAUTHORITY:-}"
    XDG_SESSION_TYPE: "${XDG_SESSION_TYPE:-}"

services:

  base:
    <<: *base_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-base
    build:
      <<: *base_build_settings
      dockerfile: dev/dockerfiles/runtime/base.Dockerfile
      args:
        UID: ${UID:-1000}
        AMD64_BASE: nvidia/cuda:${CUDA_VERSION:-11.6.2}-runtime-${LINUX_VERSION:-ubuntu20.04}
        ARM64_BASE: nvcr.io/nvidia/l4t-cuda:${CUDA_VERSION:-11.4.14}-runtime
        DEVEL_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-devel-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-main

  main:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-main
    build:
      <<: *main_build_settings
      dockerfile: dev/dockerfiles/runtime/main.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-base

  demo:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-demo
    build:
      <<: *main_build_settings
      dockerfile: dev/dockerfiles/runtime/demo.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-base

  glfw:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-glfw
    build:
      <<: *main_build_settings
      dockerfile: dev/dockerfiles/runtime/glfw.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-base

  cudf:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-cudf
    build:
      <<: *main_build_settings
      dockerfile: dev/dockerfiles/runtime/cudf.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-base

  sql:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-sql
    build:
      <<: *main_build_settings
      dockerfile: dev/dockerfiles/runtime/sql.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-base

  cuml:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-cuml
    build:
      <<: *main_build_settings
      dockerfile: dev/dockerfiles/runtime/cuml.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-base

  cugraph:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-cugraph
    build:
      <<: *main_build_settings
      dockerfile: dev/dockerfiles/runtime/cugraph.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-base

  cuspatial:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-cuspatial
    build:
      <<: *main_build_settings
      dockerfile: dev/dockerfiles/runtime/cuspatial.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-base

  io:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-io
    build:
      <<: *main_build_settings
      dockerfile: dockerfiles/runtime/io.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-runtime-node${NODE_VERSION:-16.10.0}-cuda${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-base

  notebook:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-notebook
    build:
      <<: *main_build_settings
      dockerfile: dev/dockerfiles/runtime/notebook.Dockerfile
      args:
        <<: *main_build_args
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-22.06.00}-runtime-node${NODE_VERSION:-18.2.0}-cuda${CUDA_VERSION:-11.6.2}-${LINUX_VERSION:-ubuntu20.04}-demo
    volumes:
      - "/etc/fonts:/etc/fonts:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/usr/share/fonts:/usr/share/fonts:ro"
      - "/usr/share/icons:/usr/share/icons:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket"
      - "${XDG_RUNTIME_DIR:-/run/user/$UID}:${XDG_RUNTIME_DIR:-/run/user/$UID}"
    environment: &main_environment_settings
      # Colorize the terminal in the container if possible
      TERM: "${TERM:-}"
      NVIDIA_DRIVER_CAPABILITIES: all
      # Use the host's X11 display
      DISPLAY: "${DISPLAY:-}"
      XAUTHORITY: "${XAUTHORITY:-}"
      XDG_SESSION_TYPE: "${XDG_SESSION_TYPE:-}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR:-/run/user/$UID}"
      DBUS_SESSION_BUS_ADDRESS: "${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/$UID/bus}"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
