version: "3.8"

x-base-settings: &base_service_settings
  tty: true
  env_file: .env
  network_mode: host
  build: &base_build_settings
    context: .
    x-bake:
      platforms:
        - linux/arm64
      output: type=docker
  environment: &base_environment_settings
    # Colorize the terminal in the container if possible
    TERM: "${TERM:-}"
    NVIDIA_DRIVER_CAPABILITIES: all
  deploy:
    resources:
      reservations:
        devices:
          - capabilities:
            - gpu

x-main-service-settings: &main_service_settings
  <<: *base_service_settings
  volumes:
    - ".:/opt/rapids/node:rw"
    - "/etc/fonts:/etc/fonts:ro"
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/usr/share/fonts:/usr/share/fonts:ro"
    - "/usr/share/icons:/usr/share/icons:ro"
    - "/etc/timezone:/etc/timezone"
    - "/etc/localtime:/etc/localtime"
    - "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket"
    - "${XDG_RUNTIME_DIR:-/run/user/$UID}:${XDG_RUNTIME_DIR:-/run/user/$UID}"
  environment: &main_environment_settings
    <<: *base_environment_settings
    # Use the host's X11 display
    DISPLAY: "${DISPLAY:-}"
    XAUTHORITY: "${XAUTHORITY:-}"
    XDG_SESSION_TYPE: "${XDG_SESSION_TYPE:-}"
    XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR:-/run/user/$UID}"
    LIBCUDF_KERNEL_CACHE_PATH: "/opt/rapids/node/.cache/jit"
    DBUS_SESSION_BUS_ADDRESS: "${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/$UID/bus}"
    GCC_COLORS: "${GCC_COLORS:-error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01}"
  cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
  security_opt:
    - apparmor=unconfined

services:

  main:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-devel-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dev/dockerfiles/devel/main.Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION:-16.10.0}
        AMD64_BASE: ${AMD64_BASE:-nvidia/cudagl:11.4.2-devel-ubuntu20.04}
        ARM64_BASE: ${ARM64_BASE:-nvcr.io/nvidia/l4t-cuda:10.2.460-runtime}
        SCCACHE_REGION: "${SCCACHE_REGION:-}"
        SCCACHE_BUCKET: "${SCCACHE_BUCKET:-}"
        SCCACHE_IDLE_TIMEOUT: "${SCCACHE_IDLE_TIMEOUT:-}"
        AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
        AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"

  packages:
    <<: *base_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-devel-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-packages-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dev/dockerfiles/devel/package.Dockerfile
      args:
        CUDAARCHS: "${CUDAARCHS:-NATIVE}"
        PARALLEL_LEVEL: "${PARALLEL_LEVEL:-4}"
        RAPIDS_VERSION: "${RAPIDS_VERSION:-21.12.00}"
        SCCACHE_REGION: "${SCCACHE_REGION:-us-west-2}"
        SCCACHE_BUCKET: "${SCCACHE_BUCKET:-node-rapids-sccache}"
        SCCACHE_IDLE_TIMEOUT: "${SCCACHE_IDLE_TIMEOUT:-32768}"
        AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
        AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-devel-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}

  notebook:
    <<: *main_service_settings
    image: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-devel-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-notebook-${ARCH:-amd64}
    build:
      <<: *base_build_settings
      dockerfile: dev/dockerfiles/devel/notebook.Dockerfile
      args:
        FROM_IMAGE: ${REPOSITORY:-ghcr.io/rapidsai/node}:${RAPIDS_VERSION:-21.12.00}-devel-node${NODE_VERSION:-16.10.0}-cudagl${CUDA_VERSION:-11.4.2}-${LINUX_VERSION:-ubuntu20.04}-main-${ARCH:-amd64}
    environment:
      <<: *main_environment_settings
      QT_AUTO_SCREEN_SCALE_FACTOR: 0
