module.exports = {
  entryPointStrategy: 'packages',
  entryPoints: [
    'modules/cuda',
    'modules/rmm',
    'modules/cudf',
    'modules/cuml',
    'modules/cugraph',
    'modules/cuspatial',
    'modules/io',
    'modules/deck',
    'modules/glfw',
    'modules/jsdom',
    'modules/webgl',
  ],
  out: 'doc',
  name: 'RAPIDS',
  tsconfig: 'tsconfig.json',
  hideGenerator: true,
  excludePrivate: true,
  excludeProtected: true,
  excludeExternals: true,
};
