name: build-and-publish-image

description: "Build and publish a Docker image"

inputs:
  push:
    default: false
    required: false
    description: "Push the image to the container registry"
  file:
    required: true
    description: "Dockerfile to build"
  tags:
    required: true
    description: "Image tags to publish"
  secrets:
    default: ""
    required: false
    description: "Optional secrets to mount"
  platforms:
    default: ""
    required: false
    description: "Optional platforms to build"
  build-args:
    default: ""
    required: false
    description: "Optional build arguments to use"
  registry-url:
    default: "ghcr.io"
    required: false
    description: "URL of the container registry to use"
  registry-username:
    default: ""
    required: false
    description: "URL of the container registry to use"
  registry-password:
    default: ""
    required: false
    description: "URL of the container registry to use"

outputs:
  digest:
    description: "Image content-addressable identifier"
    value: ${{ steps.docker-build.outputs.digest }}
  metadata:
    description: "Build result metadata"
    value: ${{ steps.docker-build.outputs.metadata }}

runs:
  using: composite
  steps:
    - name: Free up disk space
      shell: bash
      run: |
        df -h
        docker images
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        sudo rm -rf /opt/ghc "$CONDA" \
          /usr/share/swift \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /home/linuxbrew/.linuxbrew \
          /opt/hostedtoolcache/CodeQL
        docker rmi $(docker image ls -aq) || true
        df -h
        docker images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug
    - name: Login to registry
      uses: docker/login-action@v1
      if: inputs.push == true
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}
    - name: Build image
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ inputs.push }}
        file: ${{ inputs.file }}
        tags: ${{ inputs.tags }}
        secrets: ${{ inputs.secrets }}
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build-args }}
