name: build-and-publish-image

description: "Build and publish a Docker image"

inputs:
  file:
    required: true
    description: "Dockerfile to build"
  tags:
    required: true
    description: "Image tags to publish"
  pull:
    default: false
    required: false
    description: "Attempt to pull a newer version of the image (default false)"
  push:
    default: false
    required: false
    description: "Push the image to the container registry (default false)"
  platforms:
    default: "linux/amd64"
    required: false
    description: "Platforms to build"
  build-args:
    default: ""
    required: false
    description: "Build arguments to use"
  registry-url:
    default: ""
    required: false
    description: "Address of container registry"
  registry-username:
    default: ""
    required: false
    description: "Username used to log in to the container registry"
  registry-password:
    default: ""
    required: false
    description: "Password used to log in to the container registry"
  AWS_ACCESS_KEY_ID:
    default: ""
    required: false
    description: "AWS access id for writing to the shared sccache S3 bucket"
  AWS_SECRET_ACCESS_KEY:
    default: ""
    required: false
    description: "AWS secret key for writing to the shared sccache S3 bucket"
  RAPIDSAI_GITHUB_ACCESS_TOKEN:
    default: ""
    required: false
    description: "GH token for cloning private RAPIDS repositories"

outputs:
  digest:
    description: "Image content-addressable identifier"
    value: ${{ steps.docker-build.outputs.digest }}
  metadata:
    description: "Build result metadata"
    value: ${{ steps.docker-build.outputs.metadata }}

runs:
  using: composite
  steps:
    - name: Free up disk space
      shell: bash
      run: |
        df -h
        docker images
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        sudo rm -rf /opt/ghc "$CONDA" \
          /usr/share/swift \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /home/linuxbrew/.linuxbrew \
          /opt/hostedtoolcache/CodeQL
        docker rmi $(docker image ls -aq) || true
        df -h
        docker images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug
    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}
    - name: Initialize sccache_credentials
      shell: bash
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ inputs.AWS_ACCESS_KEY_ID }}" >> /tmp/sccache_credentials
        echo "AWS_SECRET_ACCESS_KEY=${{ inputs.AWS_SECRET_ACCESS_KEY }}" >> /tmp/sccache_credentials
        echo "RAPIDSAI_GITHUB_ACCESS_TOKEN=${{ inputs.RAPIDSAI_GITHUB_ACCESS_TOKEN }}" >> /tmp/sccache_credentials
    - name: Build image
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: ${{ inputs.pull }}
        push: ${{ inputs.push }}
        file: ${{ inputs.file }}
        tags: ${{ inputs.tags }}
        load: ${{ inputs.push == 'false' }}
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build-args }}
        labels: |
          org.opencontainers.image.vendor=NVIDIA
          org.opencontainers.image.source=https://github.com/rapidsai/node
        secret-files: |
          "sccache_credentials=/tmp/sccache_credentials"
    - name: Clean up
      shell: bash
      run: |
        rm /tmp/sccache_credentials
