name: build-and-publish-image

description: "Build and publish a Docker image"

inputs:
  file:
    required: true
    description: "Dockerfile to build"
  tags:
    required: true
    description: "Image tags to publish"
  pull:
    default: false
    required: false
    description: "Attempt to pull a newer version of the image (default false)"
  push:
    default: false
    required: false
    description: "Push the image to the container registry (default false)"
  context:
    default: "."
    required: true
    description: "Path to image build context"
  platforms:
    default: "linux/amd64"
    required: false
    description: "Platforms to build"
  buildx-driver-opts:
    default: ""
    required: false
    description: "List of additional driver-specific options"
  build-args:
    default: ""
    required: false
    description: "Build arguments to use"
  registry-url:
    default: ""
    required: false
    description: "Address of container registry"
  registry-username:
    default: ""
    required: false
    description: "Username used to log in to the container registry"
  registry-password:
    default: ""
    required: false
    description: "Password used to log in to the container registry"

outputs:
  digest:
    description: "Image content-addressable identifier"
    value: ${{ steps.docker-build.outputs.digest }}
  metadata:
    description: "Build result metadata"
    value: ${{ steps.docker-build.outputs.metadata }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx context
      shell: bash
      run: |
        docker context create builders
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        endpoint: builders
        buildkitd-flags: --debug
        driver-opts: ${{ inputs.buildx-driver-opts }}
    - name: Login to container registry
      if: inputs.push == 'true'
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}
    - name: Build image
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        pull: ${{ inputs.pull }}
        push: ${{ inputs.push }}
        file: ${{ inputs.file }}
        tags: ${{ inputs.tags }}
        context: ${{ inputs.context }}
        load: ${{ inputs.push == false }}
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build-args }}
        labels: |
          org.opencontainers.image.vendor=NVIDIA
          org.opencontainers.image.source=https://github.com/rapidsai/node
