name: build-and-publish-image

description: "Build and publish a Docker image"

inputs:
  push:
    default: false
    required: false
    description: "Push the image to the container registry"
  file:
    required: true
    description: "Dockerfile to build"
  tags:
    required: true
    description: "Image tags to publish"
  secrets:
    default: ""
    required: false
    description: "Optional secrets to mount"
  platforms:
    default: ""
    required: false
    description: "Optional platforms to build"
  build-args:
    default: ""
    required: false
    description: "Optional build arguments to use"
  AWS_ACCESS_KEY_ID:
    default: ""
    required: false
    description: "Optional AWS access id for writing to the shared sccache S3 bucket"
  AWS_SECRET_ACCESS_KEY:
    default: ""
    required: false
    description: "Optional AWS secret key for writing to the shared sccache S3 bucket"

outputs:
  digest:
    description: "Image content-addressable identifier"
    value: ${{ steps.docker-build.outputs.digest }}
  metadata:
    description: "Build result metadata"
    value: ${{ steps.docker-build.outputs.metadata }}

runs:
  using: composite
  steps:
    - name: Free up disk space
      shell: bash
      run: |
        df -h
        docker images
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        sudo rm -rf /opt/ghc "$CONDA" \
          /usr/share/swift \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /home/linuxbrew/.linuxbrew \
          /opt/hostedtoolcache/CodeQL
        docker rmi $(docker image ls -aq) || true
        df -h
        docker images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug
    - name: Build image
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ inputs.push }}
        file: ${{ inputs.file }}
        tags: ${{ inputs.tags }}
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build-args }}
        secrets: |
          "AWS_ACCESS_KEY_ID=${{ inputs.AWS_ACCESS_KEY_ID }}"
          "AWS_SECRET_ACCESS_KEY=${{ inputs.AWS_SECRET_ACCESS_KEY }}"
