name: build-and-publish-image

description: "Build and publish a Docker image"

inputs:
  file:
    required: true
    description: "Dockerfile to build"
  tags:
    required: true
    description: "Image tags to publish"
  secrets:
    default: ""
    required: false
    description: "Optional secrets to mount"
  platforms:
    default: ""
    required: false
    description: "Optional platforms to build"
  build-args:
    default: ""
    required: false
    description: "Optional build arguments to use"

outputs:
  digest:
    description: "Image content-addressable identifier"
    value: ${{ steps.docker-build.outputs.digest }}
  metadata:
    description: "Build result metadata"
    value: ${{ steps.docker-build.outputs.metadata }}

runs:
  using: composite
  steps:
    - name: Free up disk space
      run: |
        df -h
        docker images
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        sudo rm -rf /opt/ghc "$CONDA" \
          /usr/share/swift \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /home/linuxbrew/.linuxbrew \
          /opt/hostedtoolcache/CodeQL
        docker rmi $(docker image ls -aq) || true
        df -h
        docker images
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.token }}
        password: ${{ github.repository_owner }}
    - id: docker-build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        file: ${{ inputs.file }}
        tags: ${{ inputs.tags }}
        secrets: ${{ inputs.secrets }}
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build-args }}
