name: Build and push image

on:
  workflow_call:
    inputs:
      file:
        type: string
        required: true
      image:
        default: ""
        type: string
        required: true
      from_:
        default: ""
        type: string
        required: false
      build:
        default: ""
        type: string
        required: false
      devel:
        default: ""
        type: string
        required: false
      push:
        default: true
        type: boolean
        required: false
      pull:
        default: true
        type: boolean
        required: false
      build-args:
        default: ""
        type: string
        required: false
      manual-build:
        type: boolean
        default: false
        required: false
      node-version:
        type: string
        required: false
        default: "24.14.1"
      files-to-diff:
        default: ""
        type: string
        required: false
      generate-creds:
        default: false
        type: boolean
        required: false
        description: "Generate sccache and sccache-dist credentials"

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  discussions: none
  id-token: write
  issues: none
  packages: write
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    runs-on: ${{ fromJSON(github.repository != 'rapidsai/node' && '"ubuntu-latest"' || format('"linux-{0}-cpu4"', matrix.ARCH)) }}
    strategy:
      fail-fast: true
      matrix:
        ARCH: ["amd64", "arm64"]
        CUDA: ["12.9.1", "13.1.1"]
        LINUX: ["ubuntu24.04"]
    outputs:
      digest_amd64: ${{ steps.build.outputs.digest_amd64 }}
      digest_arm64: ${{ steps.build.outputs.digest_arm64 }}
      name: ${{ steps.vars.outputs.name }}
      repo: ${{ steps.vars.outputs.repo }}
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - name: Dump runner context
        shell: bash
        run: |
          echo "${{ toJSON(runner) }}";
          echo "is_gha_runner=${{ runner.environment != 'self-hosted' }}" >> "$GITHUB_ENV";

      - name: Set up self-hosted runner
        if: ${{ env.is_gha_runner != 'true' }}
        shell: bash
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends jq git-lfs openssh-client
          sudo sed -ri "s@$HOME@${{ runner.workspace }}@g" /etc/passwd
          sudo chown -R $(id -u):$(id -g) "${{ runner.workspace }}"
          echo "HOME=${{ runner.workspace }}" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          lfs: true
          fetch-depth: 0

      - name: Checkout LFS
        shell: bash
        run: git lfs checkout

      - name: Free up disk space
        if: ${{ env.is_gha_runner == 'true' }}
        uses: ./.github/actions/free-disk-space
        with:
          tool_cache: ${{ runner.tool_cache }}

      - name: Get changed files
        id: changed
        if: ${{ ! inputs.manual-build }}
        uses: rapidsai/shared-actions/changed-files@main
        with:
          files_yaml: |
            all: |
              .npmrc
              yarn.lock
              lerna.json
              ${{ inputs.file }}
              ${{ inputs.files-to-diff }}
              .github/workflows/merge.pr.yml
              .github/workflows/build-and-push-image.yml
              .github/actions/build-and-publish-image/action.yml

      - uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        if: inputs.generate-creds == 'true' && env.is_gha_runner != 'true'
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 43200 # 12h

      - id: vars
        name: Set environment variables
        shell: bash
        env:
          GENERATE_CREDENTIALS: ${{ inputs.generate-creds }}
          SCACHE_DIST_AUTH_TOKEN: ${{ secrets.SCCACHE_GH_PAT }}
        run: |

          NODE="${{ inputs.node-version }}"
          PARALLEL_LEVEL="${PARALLEL_LEVEL:-4}"
          VERSION="$(cat lerna.json | jq -r '.version')"
          image_type="$(echo "${{ inputs.image }}" | cut -d'-' -f1)"
          image_name="$(echo "${{ inputs.image }}" | cut -d'-' -f2)"
          REPOSITORY="ghcr.io/${{ github.repository }}"
          CUDA_VERSION_MAJOR="$(echo "${{ matrix.CUDA }}" | cut -d'.' -f1)"
          CUDA_VERSION_MINOR="$(echo "${{ matrix.CUDA }}" | cut -d'.' -f2)"
          CUDA_VERSION_PATCH="$(echo "${{ matrix.CUDA }}" | cut -d'.' -f3)"
          RAPIDS_VERSION="$(cat package.json | jq -r '.config.rapids_version')"
          files_changed="${{
            inputs.manual-build == 'true' ||
            fromJSON(steps.changed.outputs.changed_file_groups).all == 'true' ||
            fromJSON(steps.changed.outputs.changed_file_groups).all_any_deleted == 'true' }}"

          echo "NODE=$NODE" >> "$GITHUB_ENV";
          echo "VERSION=$VERSION" >> "$GITHUB_ENV";
          echo "image_type=$image_type" >> "$GITHUB_ENV";
          echo "image_name=$image_name" >> "$GITHUB_ENV";
          echo "REPOSITORY=$REPOSITORY" >> "$GITHUB_ENV";
          echo "files_changed=$files_changed" >> "$GITHUB_ENV";
          echo "PARALLEL_LEVEL=$PARALLEL_LEVEL" >> "$GITHUB_ENV";
          echo "RAPIDS_VERSION=$RAPIDS_VERSION" >> "$GITHUB_ENV";
          echo "CUDA_VERSION_MAJOR=$CUDA_VERSION_MAJOR" >> "$GITHUB_ENV";
          echo "CUDA_VERSION_MINOR=$CUDA_VERSION_MINOR" >> "$GITHUB_ENV";
          echo "CUDA_VERSION_PATCH=$CUDA_VERSION_PATCH" >> "$GITHUB_ENV";

          if [[ "${GENERATE_CREDENTIALS:-false}" == true ]]; then
            if [[ "$is_gha_runner" != true ]]; then
              cat <<EOF >> .creds
          AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
          AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          SCCACHE_DIST_AUTH_TOKEN=$(
            curl -fsSL -H "Authorization: Bearer $(
              curl -fsSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=token.rapids.nvidia.com" \
            | jq -r '.value'
            )" https://token.rapids.nvidia.com/gh/token/exchange \
          | jq -r '.token')
          EOF
              echo "SECRET_FILES=sccache_credentials=.creds" >> "$GITHUB_ENV";
            elif test -n "${SCACHE_DIST_AUTH_TOKEN:+x}"; then
              gh extension install nv-gha-runners/gh-nv-gha-aws
              GH_TOKEN="$SCACHE_DIST_AUTH_TOKEN" \
                gh nv-gha-aws org nvidia \
                  --duration 43200 \
                  --output shell \
                  --aud "sts.amazonaws.com" \
                  --idp-url "https://token.rapids.nvidia.com" \
                  --role-arn "arn:aws:iam::279114543810:role/rapids-token-sccache-devs" \
              | sed 's/export //' \
              | cat - <(cat <<< "SCCACHE_DIST_AUTH_TOKEN=$SCACHE_DIST_AUTH_TOKEN") \
              > .creds
              echo "SECRET_FILES=sccache_credentials=.creds" >> "$GITHUB_ENV";
            fi
          fi

          echo "BUILD_ARGS<<EOF" >> "$GITHUB_ENV";

          if [[ -n "${{ inputs.build-args }}" ]]; then
            echo -e "${{ inputs.build-args }}" >> "$GITHUB_ENV";
          fi

          if [[ "${{ inputs.image }}" == devel-main ]]; then
            echo "ARM64_BASE=nvidia/cuda:${{ matrix.CUDA }}-devel-${{ matrix.LINUX }}" >> "$GITHUB_ENV";
            echo "AMD64_BASE=nvidia/cuda:${{ matrix.CUDA }}-devel-${{ matrix.LINUX }}" >> "$GITHUB_ENV";
          elif [[ "${{ inputs.image }}" == runtime-base ]]; then
            echo "ARM64_BASE=nvidia/cuda:${{ matrix.CUDA }}-base-${{ matrix.LINUX }}" >> "$GITHUB_ENV";
            echo "AMD64_BASE=nvidia/cuda:${{ matrix.CUDA }}-base-${{ matrix.LINUX }}" >> "$GITHUB_ENV";
          fi

          if [[ -n "${{ inputs.from_ }}" ]]; then
            from__type="$(echo "${{ inputs.from_ }}" | cut -d'-' -f1)";
            from__name="$(echo "${{ inputs.from_ }}" | cut -d'-' -f2)";
            from_image="${REPOSITORY}:${VERSION}-${from__type}-node${NODE}-cuda${CUDA_VERSION_MAJOR}-${{ matrix.LINUX }}-${from__name}";
            echo "FROM_IMAGE=${from_image}" >> "$GITHUB_ENV";
          fi

          if [[ -n "${{ inputs.build }}" ]]; then
            build_type="$(echo "${{ inputs.build }}" | cut -d'-' -f1)";
            build_name="$(echo "${{ inputs.build }}" | cut -d'-' -f2)";
            build_image="${REPOSITORY}:${VERSION}-${build_type}-node${NODE}-cuda${CUDA_VERSION_MAJOR}-${{ matrix.LINUX }}-${build_name}";
            echo "BUILD_IMAGE=${build_image}" >> "$GITHUB_ENV";
          fi

          if [[ -n "${{ inputs.devel }}" ]]; then
            devel_type="$(echo "${{ inputs.devel }}" | cut -d'-' -f1)";
            devel_name="$(echo "${{ inputs.devel }}" | cut -d'-' -f2)";
            devel_image="${REPOSITORY}:${VERSION}-${devel_type}-node${NODE}-cuda${CUDA_VERSION_MAJOR}-${{ matrix.LINUX }}-${devel_name}";
            echo "DEVEL_IMAGE=${devel_image}" >> "$GITHUB_ENV";
          fi

          echo "EOF" >> "$GITHUB_ENV";

          TAG="${VERSION}-${image_type}-node${NODE}-cuda${CUDA_VERSION_MAJOR}-${{ matrix.LINUX }}-${image_name}";
          NAME="${REPOSITORY}:${TAG}";

          echo "tag=${TAG}" >> "$GITHUB_OUTPUT";
          echo "name=${NAME}" >> "$GITHUB_OUTPUT";
          echo "repo=${REPOSITORY}" >> "$GITHUB_OUTPUT";
          echo "IMAGE_NAME=${NAME}" >> "$GITHUB_ENV";

      - id: build
        name: Build image
        if: ${{ inputs.manual-build || env.files_changed == 'true' }}
        uses: ./.github/actions/build-and-publish-image
        with:
          arch: ${{ matrix.ARCH }}
          pull: ${{ inputs.pull }}
          push: ${{ inputs.push }}
          file: ${{ inputs.file }}
          repo: ${{ env.REPOSITORY }}
          registry-url: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ github.token }}
          secret-files: ${{ env.SECRET_FILES }}
          build-args: |
            ${{ env.BUILD_ARGS }}
            "NODE_VERSION=${{ env.NODE }}"
            "LINUX_VERSION=${{ matrix.LINUX }}"
            "RAPIDS_VERSION=${{ env.RAPIDS_VERSION }}"

  push:
    if: inputs.push == 'true'
    name: Push to ghcr.io
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - id: push
        name: Push manifest to ghcr.io
        shell: bash --noprofile --norc -x -eo pipefail {0}
        env:
          digest_amd64: ${{ needs.build.outputs.digest_amd64 }}
          digest_arm64: ${{ needs.build.outputs.digest_arm64 }}
          name: ${{ needs.build.outputs.name }}
          repo: ${{ needs.build.outputs.repo }}
          repo_prefix: "ghcr.io/${{ github.actor }}"
        run: |
          # Create the multiarch manifest
          docker buildx imagetools create --tag "${name}" "${digest_amd64}" "${digest_arm64}";
          echo "repo=${repo#${repo_prefix}/}" >> "$GITHUB_OUTPUT";

      - name: Clean up untagged images
        uses: snok/container-retention-policy@3b0972b2276b171b212f8c4efbca59ebba26eceb
        with:
          cut-off: 1hr
          tag-selection: untagged
          token: "${{ github.token }}"
          image-tags: "${{ needs.build.outputs.tag }}"
          image-names: "${{ steps.push.outputs.repo }}"
          skip-shas: "${{ needs.build.outputs.digest_amd64 }} ${{ needs.build.outputs.digest_arm64 }}"
          account: "${{ github.actor == github.triggering_actor && 'user' || github.actor }}"
