name: docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docker-images:
    name: Build docker images
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        CUDA_VERSION: [11.0.3, 11.2.2, 11.4.0]
        LINUX_VERSION: [ubuntu18.04, ubuntu20.04]
    env:
      ARCH: amd64
      NODE_VERSION: 16.5.0
      RAPIDS_VERSION: 21.08.00
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: builder
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet $CONDA
      - name: Build devel and runtime containers
        run: |
          CUDA_VERSION=${{ matrix.CUDA_VERSION }}
          LINUX_VERSION=${{ matrix.LINUX_VERSION }}
          yarn docker:build:release
