name: Build pull request

on:
  push:
    branches:
      - 'pull-request/**'

permissions:
  contents: write
  id-token: write

jobs:
  build-pull-request:
    name: Build pull request
    runs-on: ${{ fromJSON(github.repository != 'rapidsai/node' && '"ubuntu-latest"' || format('"linux-{0}-cpu16"', matrix.ARCH)) }}
    strategy:
      fail-fast: false
      matrix:
        ARCH: ["amd64", "arm64"]
        CUDA: ["12.9.1", "13.1.1"]
        LINUX: ["ubuntu24.04"]
    env:
      UCX: "1.20.0"
      NODE: "24.14.1"
      REGISTRY: "ghcr.io"
      DOCKER_BUILDKIT: "1"
      DOCKER_CLI_HINTS: "false"
      DOCKER_SCAN_SUGGEST: "false"
    steps:
      - name: Dump runner context
        shell: bash --noprofile --norc -eo pipefail {0}
        env:
          CUDA: "${{ matrix.CUDA }}"
        run: |
          echo "${{ toJSON(runner) }}"
          echo "CUDA_VERSION_MAJOR=$(cut -d'.' -f1 <<< "${CUDA}")" >> "$GITHUB_ENV"
          echo "CUDA_VERSION_MINOR=$(cut -d'.' -f2 <<< "${CUDA}")" >> "$GITHUB_ENV"
          echo "CUDA_VERSION_PATCH=$(cut -d'.' -f3 <<< "${CUDA}")" >> "$GITHUB_ENV"

      - name: Setup proxy cache
        if: runner.environment == 'self-hosted'
        uses: nv-gha-runners/setup-proxy-cache@c5e8f6fd27b493abfd6af230e6a5d4bf43d1d766
        continue-on-error: true
        with:
          enable-apt: true

      - name: Set up self-hosted runner
        if: runner.environment == 'self-hosted'
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends jq git-lfs
          # sudo sed -ri "s@$HOME@${{ runner.workspace }}@g" /etc/passwd
          # sudo chown -R $(id -u):$(id -g) "${{ runner.workspace }}"
          # echo "HOME=${{ runner.workspace }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          lfs: true
          fetch-depth: 0

      - name: Checkout LFS
        shell: bash --noprofile --norc -eo pipefail {0}
        run: git lfs checkout

      - name: Get PR target branch info
        id: get-pr-info
        uses: ./.github/actions/get-pr-info

      - name: Get changed files
        id: changed
        uses: step-security/changed-files@60967b822d3001fa82242f8d6b4ed46bc3600a68 # v47.0.1
        with:
          base_sha: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.sha }}
          sha: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).head.sha }}
          files_yaml: |
            dev:
              - dev/dockerfiles/devel/main.Dockerfile
            src:
              - yarn.lock
              - lerna.json
              - package.json
              - modules/**/*.c
              - modules/**/*.h
              - modules/**/*.ts
              - modules/**/*.js
              - modules/**/*.cu
              - modules/**/*.cuh
              - modules/**/*.cpp
              - modules/**/*.hpp
              - modules/**/*.json
              - modules/**/*.cmake
              - modules/**/*.tsconfig
              - modules/**/package.json
              - modules/**/CMakeLists.txt

      - name: Update runner environment
        env:
          dev_changed: "${{ steps.changed.outputs.dev_any_changed == 'true' }}"
          src_changed: "${{ steps.changed.outputs.src_any_changed == 'true' ||
                            steps.changed.outputs.src_any_deleted == 'true' }}"
          REPOSITORY: "${{ env.REGISTRY }}/${{ github.repository }}"
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          VERSION="$(jq -r '.version' lerna.json)"
          RAPIDS_VERSION="$(jq -r '.config.rapids_version' package.json)"
          cat <<EOF >> "$GITHUB_ENV"
          CUDAARCHS=RAPIDS
          MAIN_IMG=${REPOSITORY}:${VERSION}-devel-node${NODE}-cuda${CUDA_VERSION_MAJOR}-${{ matrix.LINUX }}-main
          NVCC_APPEND_FLAGS=-t=100
          RAPIDS_VERSION=${RAPIDS_VERSION}
          VERSION=${VERSION}
          dev_changed=${dev_changed}
          src_changed=${src_changed}
          EOF

      # - name: Cache C++ dependencies
      #   if: env.dev_changed == 'true' || env.src_changed == 'true'
      #   uses: actions/cache@v2
      #   with:
      #     key: ${{ runner.os }}-${{ env.VERSION }}-node${{ env.NODE }}-cuda${{ env.CUDA_VERSION_MAJOR }}-${{ matrix.LINUX }}-cache-${{ hashFiles('**/modules/**/CMakeLists.txt', '**/modules/**/*.cmake') }}
      #     path: |
      #       node/.cache/binary
      #       node/.cache/source

      # - name: Cache node_modules
      #   if: env.dev_changed == 'true' || env.src_changed == 'true'
      #   uses: actions/cache@v2
      #   with:
      #     key: ${{ runner.os }}-${{ env.VERSION }}-node${{ env.NODE }}-cuda${{ env.CUDA_VERSION_MAJOR }}-${{ matrix.LINUX }}-node_modules-${{ hashFiles('**/yarn.lock', '**/package.json') }}
      #     path: |
      #       .yarn
      #       .cache
      #       node/node_modules

      - name: Setup sccache
        id: sccache
        if: env.dev_changed == 'true' || env.src_changed == 'true'
        uses: ./.github/actions/setup-sccache
        with:
          custom-gh-token: ${{ secrets.SCCACHE_GH_PAT }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Free up disk space
        if: runner.environment == 'github-hosted' && (env.dev_changed == 'true' || env.src_changed == 'true')
        uses: ./.github/actions/free-disk-space
        with:
          tool_cache: ${{ runner.tool_cache }}

      - name: Build
        if: env.dev_changed == 'true' || env.src_changed == 'true'
        shell: bash --noprofile --norc -eo pipefail {0}
        env:
          ARCH: ${{ matrix.ARCH }}
          CUDA: ${{ matrix.CUDA }}
          LINUX: ${{ matrix.LINUX }}
          PARALLEL_LEVEL: ${{ steps.sccache.outputs.parallel_level }}
        run: |
          function begin_group() {
            local blue="34"
            echo -e "::group::\e[${blue}m${1:-}\e[0m"
          }

          function end_group() {
            local name="${1:-}"
            local build_status="${2:-0}"
            local red="31"

            echo "::endgroup::"
            if [ "$build_status" -ne 0 ]; then
              echo -e "::error::\e[${red}m ${name} - Failed (⬆️ click above for full log ⬆️)\e[0m"
            fi
          }

          function run_command() {
            local -;
            set -euo pipefail;

            local group="${1:-}";
            shift;
            local command=("$@");
            local exit_code="0";

            begin_group "$group";

            echo "Working directory: $(pwd)";
            echo "Running command: ${command[*]}";
            "${command[@]}" || exit_code=$?;

            end_group "$group" "$exit_code"

            return "$exit_code"
          }

          has_image="false"

          if run_command "Pull ${MAIN_IMG}" \
            docker pull --platform "linux/${ARCH}" "${MAIN_IMG}"; then
            has_image="true"
          fi

          if [[ ! "$has_image" ]] || [[ "$dev_changed" ]]; then
            run_command "Build ${MAIN_IMG}" \
              docker build --pull --force-rm \
                --ulimit "nofile=500000:500000" \
                --build-arg UCX_VERSION="${UCX}" \
                --build-arg NODE_VERSION="${NODE}" \
                --build-arg LINUX_VERSION="${LINUX}" \
                --build-arg AMD64_BASE="nvidia/cuda:${CUDA}-devel-${LINUX}" \
                --build-arg ARM64_BASE="nvidia/cuda:${CUDA}-devel-${LINUX}" \
                -f dev/dockerfiles/devel/main.Dockerfile \
                -t "${MAIN_IMG}" \
                .
          fi

          run_command "Build node-rapids" \
           docker run --rm -t \
              --user "$(id -u):$(id -g)" \
              --ulimit "nofile=500000:500000" \
              `# -v "$(pwd)/.yarn:/.yarn:rw"` \
              `# -v "$(pwd)/.cache:/.cache:rw"` \
              -v "$(pwd):/opt/rapids/node:rw" \
              -v "${HOME}/.aws:/opt/rapids/.aws:ro" \
              -v "${HOME}/.config:/opt/rapids/.config:ro" \
              -v "${HOME}/.gitconfig:/opt/rapids/.gitconfig:ro" \
              -e "CUDAARCHS=${CUDAARCHS}" \
              -e "PARALLEL_LEVEL=${PARALLEL_LEVEL}" \
              -e "RAPIDS_VERSION=${RAPIDS_VERSION}" \
              -e "NVCC_APPEND_FLAGS=${NVCC_APPEND_FLAGS}" \
              -e "CMAKE_BUILD_PARALLEL_LEVEL=${PARALLEL_LEVEL}" \
              "${MAIN_IMG}" \
              bash -cex "yarn --pure-lockfile --prefer-offline && yarn build"
