name: Build docker images

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-docker-images-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build-and-publish-devel-main-image:
    name: Build and publish devel main image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit
    with:
      image: devel-main
      file: dev/dockerfiles/devel/main.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
      files-to-diff: |
        .npmrc
        modules
        yarn.lock
      build-args: |
        "UCX_VERSION=1.12.1"

  build-and-publish-devel-packages-image:
    name: Build devel packages image
    needs:
      - build-and-publish-devel-main-image
    uses: ./.github/workflows/build-and-push-image-ssh.yml
    secrets: inherit
    with:
      from_: devel-main
      image: devel-packages
      file: dev/dockerfiles/devel/package.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
      files-to-diff: |
        .npmrc
        modules
        yarn.lock
        dev/dockerfiles/devel/main.Dockerfile
      build-args: |
        "CUDAARCHS=ALL"
        "SCCACHE_IDLE_TIMEOUT=32768"
        "SCCACHE_REGION=us-west-2"
        "SCCACHE_BUCKET=node-rapids-sccache"

  build-and-publish-runtime-cuda-base-image:
    name: Build runtime cuda-base image
    needs:
      - build-and-publish-devel-main-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit
    with:
      image: runtime-base
      devel: devel-main
      file: dev/dockerfiles/runtime/base.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
      build-args: |
        "UID=1000"

  build-and-publish-runtime-cudf-image:
    name: Build runtime cudf image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit
    with:
      from_: runtime-base
      image: runtime-cudf
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/cudf.Dockerfile
      files-to-diff: |
        .npmrc
        modules/(core|rmm|cuda|cudf)
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}

  build-and-publish-runtime-cuml-image:
    name: Build runtime cuml image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit
    with:
      from_: runtime-base
      image: runtime-cuml
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/cuml.Dockerfile
      files-to-diff: |
        .npmrc
        modules/(core|rmm|cuda|cudf|cuml)
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}

  build-and-publish-runtime-cugraph-image:
    name: Build runtime cugraph image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit
    with:
      from_: runtime-base
      image: runtime-cugraph
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/cugraph.Dockerfile
      files-to-diff: |
        .npmrc
        modules/(core|rmm|cuda|cudf|cugraph)
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}

  build-and-publish-runtime-cuspatial-image:
    name: Build runtime cuspatial image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit
    with:
      from_: runtime-base
      image: runtime-cuspatial
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/cuspatial.Dockerfile
      files-to-diff: |
        .npmrc
        modules/(core|rmm|cuda|cudf|cuspatial)
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}

  build-and-publish-runtime-glfw-image:
    name: Build runtime glfw image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit
    with:
      from_: runtime-base
      image: runtime-glfw
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/glfw.Dockerfile
      files-to-diff: |
        .npmrc
        modules/(core|glfw|webgl)
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}

  build-and-publish-runtime-sql-image:
    name: Build runtime sql image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit
    with:
      from_: runtime-base
      image: runtime-sql
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/sql.Dockerfile
      files-to-diff: |
        .npmrc
        modules/(core|rmm|cuda|cudf|sql)
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
      build-args: |
        "UCX_VERSION=1.12.1"

  build-and-publish-runtime-main-image:
    name: Build runtime main image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit
    with:
      from_: runtime-base
      image: runtime-main
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/main.Dockerfile
      files-to-diff: |
        .npmrc
        modules/(core|cuda|glfw|webgl|rmm|cudf|sql|cuml|cugraph|cuspatial|deck.gl|jsdom)
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
      build-args: |
        "UCX_VERSION=1.12.1"

  build-and-publish-runtime-demo-image:
    name: Build runtime demo image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit
    with:
      from_: runtime-base
      image: runtime-demo
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/demo.Dockerfile
      files-to-diff: |
        .npmrc
        modules/demo
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
      build-args: |
        "UCX_VERSION=1.12.1"

  build-and-publish-runtime-notebook-image:
    name: Build runtime notebook image
    needs:
      - build-and-publish-runtime-demo-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit
    with:
      from_: runtime-demo
      image: runtime-notebook
      file: dev/dockerfiles/runtime/notebook.Dockerfile
      files-to-diff: |
        .npmrc
        **/*.ipynb
        modules/demo
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
