name: Build docker images

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-docker-images-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  discussions: none
  id-token: write  # zizmor: ignore[excessive-permissions]
  issues: none
  packages: write  # zizmor: ignore[excessive-permissions]
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:

  build-and-publish-devel-main-image:
    name: Build devel main image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets:
      GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      SCCACHE_GH_PAT: ${{ secrets.SCCACHE_GH_PAT }}
    with:
      image: devel-main
      file: dev/dockerfiles/devel/main.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
      files-to-diff: |
        modules
      build-args: |
        "UCX_VERSION=1.20.0"

  build-and-publish-devel-packages-image:
    name: Build devel packages image
    needs:
      - build-and-publish-devel-main-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets:
      GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      SCCACHE_GH_PAT: ${{ secrets.SCCACHE_GH_PAT }}
    with:
      from_: devel-main
      image: devel-packages
      file: dev/dockerfiles/devel/package.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
      files-to-diff: |
        modules
        dev/dockerfiles/devel/main.Dockerfile
      generate-creds: true
      build-args: |
        "CUDAARCHS=RAPIDS"

  build-and-publish-runtime-cuda-base-image:
    name: Build runtime cuda-base image
    needs:
      - build-and-publish-devel-main-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets:
      GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      SCCACHE_GH_PAT: ${{ secrets.SCCACHE_GH_PAT }}
    with:
      image: runtime-base
      devel: devel-main
      file: dev/dockerfiles/runtime/base.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
      build-args: |
        "UID=1000"

  build-and-publish-runtime-cudf-image:
    name: Build runtime cudf image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets:
      GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      SCCACHE_GH_PAT: ${{ secrets.SCCACHE_GH_PAT }}
    with:
      from_: runtime-base
      image: runtime-cudf
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/cudf.Dockerfile
      files-to-diff: |
        modules/(core|rmm|cuda|cudf)
        dev/dockerfiles/runtime/base.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}

  build-and-publish-runtime-cuml-image:
    name: Build runtime cuml image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets:
      GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      SCCACHE_GH_PAT: ${{ secrets.SCCACHE_GH_PAT }}
    with:
      from_: runtime-base
      image: runtime-cuml
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/cuml.Dockerfile
      files-to-diff: |
        modules/(core|rmm|cuda|cudf|cuml)
        dev/dockerfiles/runtime/base.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}

  build-and-publish-runtime-cugraph-image:
    name: Build runtime cugraph image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets:
      GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      SCCACHE_GH_PAT: ${{ secrets.SCCACHE_GH_PAT }}
    with:
      from_: runtime-base
      image: runtime-cugraph
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/cugraph.Dockerfile
      files-to-diff: |
        modules/(core|rmm|cuda|cudf|cugraph)
        dev/dockerfiles/runtime/base.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}

  build-and-publish-runtime-cuspatial-image:
    name: Build runtime cuspatial image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets:
      GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      SCCACHE_GH_PAT: ${{ secrets.SCCACHE_GH_PAT }}
    with:
      from_: runtime-base
      image: runtime-cuspatial
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/cuspatial.Dockerfile
      files-to-diff: |
        modules/(core|rmm|cuda|cudf|cuspatial)
        dev/dockerfiles/runtime/base.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}

  build-and-publish-runtime-glfw-image:
    name: Build runtime glfw image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets:
      GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      SCCACHE_GH_PAT: ${{ secrets.SCCACHE_GH_PAT }}
    with:
      from_: runtime-base
      image: runtime-glfw
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/glfw.Dockerfile
      files-to-diff: |
        modules/(core|glfw|webgl)
        dev/dockerfiles/runtime/base.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}

  build-and-publish-runtime-main-image:
    name: Build runtime main image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets:
      GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      SCCACHE_GH_PAT: ${{ secrets.SCCACHE_GH_PAT }}
    with:
      from_: runtime-base
      image: runtime-main
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/main.Dockerfile
      files-to-diff: |
        modules/(core|cuda|glfw|webgl|rmm|cudf|cuml|cugraph|cuspatial|deck.gl|jsdom)
        dev/dockerfiles/runtime/base.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
      build-args: |
        "UCX_VERSION=1.20.0"

  build-and-publish-runtime-demo-image:
    name: Build runtime demo image
    needs:
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
    uses: ./.github/workflows/build-and-push-image.yml
    secrets:
      GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      SCCACHE_GH_PAT: ${{ secrets.SCCACHE_GH_PAT }}
    with:
      from_: runtime-base
      image: runtime-demo
      build: devel-packages
      devel: devel-main
      file: dev/dockerfiles/runtime/demo.Dockerfile
      files-to-diff: |
        modules/demo
        dev/dockerfiles/runtime/base.Dockerfile
      manual-build: ${{ github.event_name == 'workflow_dispatch' }}
      build-args: |
        "UCX_VERSION=1.20.0"

  cleanup-untagged-images:
    name: Clean up untagged images
    runs-on: ubuntu-latest
    needs:
      - build-and-publish-devel-main-image
      - build-and-publish-devel-packages-image
      - build-and-publish-runtime-cuda-base-image
      - build-and-publish-runtime-cudf-image
      - build-and-publish-runtime-cuml-image
      - build-and-publish-runtime-cugraph-image
      - build-and-publish-runtime-cuspatial-image
      - build-and-publish-runtime-glfw-image
      - build-and-publish-runtime-main-image
      - build-and-publish-runtime-demo-image
    env:
      repo: ${{ fromJSON(needs.build-and-publish-devel-main-image.outputs.amd64_cuda12_9_1).repo }}
      tags: >
        ${{ fromJSON(needs.build-and-publish-devel-main-image.outputs.amd64_cuda12_9_1).tag }}
        ${{ fromJSON(needs.build-and-publish-devel-packages-image.outputs.amd64_cuda12_9_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuda-base-image.outputs.amd64_cuda12_9_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-cudf-image.outputs.amd64_cuda12_9_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuml-image.outputs.amd64_cuda12_9_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-cugraph-image.outputs.amd64_cuda12_9_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuspatial-image.outputs.amd64_cuda12_9_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-glfw-image.outputs.amd64_cuda12_9_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-main-image.outputs.amd64_cuda12_9_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-demo-image.outputs.amd64_cuda12_9_1).tag }}
        ${{ fromJSON(needs.build-and-publish-devel-main-image.outputs.amd64_cuda13_1_1).tag }}
        ${{ fromJSON(needs.build-and-publish-devel-packages-image.outputs.amd64_cuda13_1_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuda-base-image.outputs.amd64_cuda13_1_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-cudf-image.outputs.amd64_cuda13_1_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuml-image.outputs.amd64_cuda13_1_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-cugraph-image.outputs.amd64_cuda13_1_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuspatial-image.outputs.amd64_cuda13_1_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-glfw-image.outputs.amd64_cuda13_1_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-main-image.outputs.amd64_cuda13_1_1).tag }}
        ${{ fromJSON(needs.build-and-publish-runtime-demo-image.outputs.amd64_cuda13_1_1).tag }}
      digests: >
        ${{ fromJSON(needs.build-and-publish-devel-main-image.outputs.amd64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-devel-main-image.outputs.arm64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-devel-packages-image.outputs.amd64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-devel-packages-image.outputs.arm64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuda-base-image.outputs.amd64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuda-base-image.outputs.arm64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cudf-image.outputs.amd64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cudf-image.outputs.arm64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuml-image.outputs.amd64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuml-image.outputs.arm64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cugraph-image.outputs.amd64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cugraph-image.outputs.arm64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuspatial-image.outputs.amd64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuspatial-image.outputs.arm64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-glfw-image.outputs.amd64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-glfw-image.outputs.arm64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-main-image.outputs.amd64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-main-image.outputs.arm64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-demo-image.outputs.amd64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-demo-image.outputs.arm64_cuda12_9_1).digest }}
        ${{ fromJSON(needs.build-and-publish-devel-main-image.outputs.amd64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-devel-main-image.outputs.arm64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-devel-packages-image.outputs.amd64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-devel-packages-image.outputs.arm64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuda-base-image.outputs.amd64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuda-base-image.outputs.arm64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cudf-image.outputs.amd64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cudf-image.outputs.arm64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuml-image.outputs.amd64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuml-image.outputs.arm64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cugraph-image.outputs.amd64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cugraph-image.outputs.arm64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuspatial-image.outputs.amd64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-cuspatial-image.outputs.arm64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-glfw-image.outputs.amd64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-glfw-image.outputs.arm64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-main-image.outputs.amd64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-main-image.outputs.arm64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-demo-image.outputs.amd64_cuda13_1_1).digest }}
        ${{ fromJSON(needs.build-and-publish-runtime-demo-image.outputs.arm64_cuda13_1_1).digest }}
    steps:
      - name: Clean up untagged images
        uses: snok/container-retention-policy@3b0972b2276b171b212f8c4efbca59ebba26eceb
        with:
          cut-off: 6hr
          tag-selection: untagged
          token: "${{ github.token }}"
          image-tags: "${{ env.tags }}"
          image-names: "${{ env.repo }}"
          skip-shas: "${{ env.digests }}"
          account: "${{ github.actor == github.repository_owner && 'user' || github.repository_owner }}"
