name: Create GitHub release

on:
  workflow_dispatch:
    inputs:
      rapids-version:
        type: string
        default: "26.4.0"
        description: "RAPIDS version"
      make-release:
        type: boolean
        default: false
        description: "Make Release"
      draft-release:
        type: boolean
        default: false
        description: "Draft Release"
      npm-publish:
        type: boolean
        default: false
        description: "Publish to NPM"

env:
  RAPIDS: "${{ inputs.rapids-version }}"

concurrency:
  group: release-${{ inputs.rapids-version }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:

  extract-and-publish-packages:
    name: Extract libs and publish release
    runs-on: ${{ fromJSON(github.repository != 'rapidsai/node' && '"ubuntu-latest"' || format('"linux-{0}-cpu16"', matrix.ARCH)) }}
    strategy:
      fail-fast: true
      matrix:
        CUDA: ["12.9.1", "13.1.1"]
        ARCH: ["amd64", "arm64"]
        NODE: ["24.14.1"]
        LINUX: ["ubuntu24.04"]
    steps:
      - name: Extract node native addons
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          set -x;

          mkdir -p build;

          ARCH="${{ matrix.ARCH }}";
          NODE="node${{ matrix.NODE }}";
          CUDA="cuda$(echo "${{ matrix.CUDA }}" | cut -d'.' -f1)";
          LINUX="$(echo "${{ matrix.LINUX }}" | tr '[:upper:]' '[:lower:]')";

          docker run --rm --pull always --platform "linux/${ARCH}" -v "$PWD/build:/out" \
            ghcr.io/${{ github.repository }}:${RAPIDS}-devel-${NODE}-${CUDA}-${LINUX}-packages \
            sh -c "find /opt/rapids/ -type f -name 'rapidsai_*-*-*.tar.gz' -exec cp {} /out/ \;"

          for x in cuda rmm cudf cuml cugraph cuspatial io; do
              tar -zf build/rapidsai_${x}-*.tar.gz \
                  --wildcards --strip-components=1 \
                  -C build -x "*/rapidsai_${x}*.node" \
                  --transform="s/rapidsai_${x}.node/rapidsai_${x}-${RAPIDS}-${CUDA}-${LINUX}-${ARCH}.node/" \
                  --transform="s/rapidsai_${x}_(.*)/rapidsai_${x}-${RAPIDS}-${CUDA}-${LINUX}-${ARCH}-sm\1/" ;
          done;

          rm -rf build/*.tar.gz;

      - name: Upload node native addons
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ inputs.make-release != true }}
        with:
          path: build/*.node
          name: rapidsai-native-addons

      - name: Create GitHub release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        if: ${{ inputs.make-release == true }}
        with:
          body: ""
          files: build/*.node
          tag_name: "v${{ env.RAPIDS }}"
          repository: ${{ github.repository }}
          draft: ${{ inputs.draft-release == true }}

  publish-npm-packages:
    if: ${{ inputs.make-release == true && inputs.npm-publish == true }}
    name: Publish npm packages
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        CUDA: ["13.1.1"]
        ARCH: ["amd64"]
        NODE: ["24.14.1"]
        LINUX: ["ubuntu24.04"]
    steps:
      - name: Publish npm packages
        shell: bash --noprofile --norc -x -eo pipefail {0}
        env:
          NPM_TOKEN: "${{ secrets.RAPIDSAI_OWNER_NPM_AUTOMATION_TOKEN }}"
        run: |
          set -x;

          mkdir -p build;

          ARCH="${{ matrix.ARCH }}";
          NODE="node${{ matrix.NODE }}";
          CUDA="cuda$(echo "${{ matrix.CUDA }}" | cut -d'.' -f1)";
          LINUX="$(echo "${{ matrix.LINUX }}" | tr '[:upper:]' '[:lower:]')";

          docker run --rm --pull always --platform "linux/${ARCH}" -v "$PWD/build:/out" \
            ghcr.io/${{ github.repository }}:${RAPIDS}-devel-${NODE}-${CUDA}-${LINUX}-packages \
            sh -c "find /opt/rapids/ -type f \( -name 'rapidsai-deck.gl*.tgz' -or -name 'rapidsai-[^demo]*.tgz' \) -exec cp {} /out/ \;"

          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > "$HOME/.npmrc"
          find build -type f -name 'rapidsai-*.tgz' -exec npm publish --access public ./{} \;
